"""Install CLI — ``spaice-agent <command>`` manages agent installs.

Entry point registered in pyproject.toml as ``spaice-agent``.

Commands:
    install <agent_id>              Write hook shim to ~/.Hermes/hooks/
        --with-config               Also scaffold ~/.spaice-agents/<id>/config.yaml
        --force                     Overwrite existing hook without backup
    uninstall <agent_id>            Remove hook; keep config (with --purge: remove both)
    upgrade                         Reinstall package + refresh all shims
    list                            Show all installed agents
    doctor <agent_id>               Check install health (9 checks)
    version                         Print installed package version

The hook shim is a 13-line autogenerated file that imports from
spaice_agent.hook. All business logic stays in the package, so bugs
fix once and ship via ``spaice-agent upgrade``.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from importlib import metadata, resources
from pathlib import Path
from typing import List, Optional

HOOK_SHIM_TEMPLATE = '''"""SPAICE pre-turn middleware shim — autogenerated by spaice-agent install.

Do NOT edit this file by hand. All logic lives in the spaice_agent
package; to upgrade, run ``spaice-agent upgrade``.

Generated: {generated_at}
Package version at install: {version}
Agent ID: {agent_id}
"""
from spaice_agent.hook import make_hook

AGENT_ID = "{agent_id}"
handle, register_tools = make_hook(AGENT_ID)
'''

HOOK_YAML_TEMPLATE = """name: spaice-{agent_id}
description: |
  SPAICE Agent Framework pre-turn middleware. Memory recall, search,
  and FW-1 consensus advisory. Managed by spaice-agent install.
events:
  - agent:start
"""


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def _hook_dir(agent_id: str) -> Path:
    return Path.home() / ".Hermes" / "hooks" / f"spaice-{agent_id}"


def _config_dir(agent_id: str) -> Path:
    return Path.home() / ".spaice-agents" / agent_id


def _config_path(agent_id: str) -> Path:
    return _config_dir(agent_id) / "config.yaml"


def _get_version() -> str:
    try:
        return metadata.version("spaice-agent")
    except metadata.PackageNotFoundError:
        return "unknown"


def _load_config_template() -> str:
    """Load the packaged config.yaml.template.

    Uses importlib.resources so it works from wheel installs, editable
    installs, and source checkouts.
    """
    try:
        return (
            resources.files("spaice_agent.templates")
            .joinpath("config.yaml.template")
            .read_text()
        )
    except (AttributeError, FileNotFoundError):
        # Fallback for older Python or non-standard installs
        pkg_root = Path(__file__).parent
        return (pkg_root / "templates" / "config.yaml.template").read_text()


# ---------------------------------------------------------------------------
# install
# ---------------------------------------------------------------------------

def cmd_install(args: argparse.Namespace) -> int:
    agent_id = args.agent_id
    hook_dir = _hook_dir(agent_id)

    if hook_dir.exists() and not args.force:
        backup = hook_dir.with_name(
            hook_dir.name + f".backup-{int(datetime.now().timestamp())}"
        )
        print(f"Backing up existing hook → {backup}")
        shutil.move(str(hook_dir), str(backup))

    hook_dir.mkdir(parents=True, exist_ok=True)

    # handler.py shim
    shim = HOOK_SHIM_TEMPLATE.format(
        generated_at=datetime.now(timezone.utc).isoformat(),
        version=_get_version(),
        agent_id=agent_id,
    )
    (hook_dir / "handler.py").write_text(shim)

    # HOOK.yaml
    (hook_dir / "HOOK.yaml").write_text(
        HOOK_YAML_TEMPLATE.format(agent_id=agent_id)
    )

    # Install manifest
    manifest = {
        "agent_id": agent_id,
        "package_version": _get_version(),
        "installed_at": datetime.now(timezone.utc).isoformat(),
        "shim_template_version": "1.0",
    }
    (hook_dir / ".spaice-install.json").write_text(
        json.dumps(manifest, indent=2)
    )

    print(f"✓ Installed spaice-{agent_id} hook at {hook_dir}")
    print(f"  Package version: {_get_version()}")

    # Optional: scaffold config.yaml
    if getattr(args, "with_config", False):
        cfg_path = _config_path(agent_id)
        if cfg_path.exists() and not args.force:
            print(f"  Config already exists at {cfg_path} — skipped (use --force to overwrite)")
        else:
            cfg_path.parent.mkdir(parents=True, exist_ok=True)
            template = _load_config_template()
            rendered = template.format(
                agent_id=agent_id,
                generated_at=datetime.now(timezone.utc).isoformat(),
                version=_get_version(),
            )
            cfg_path.write_text(rendered)
            print(f"✓ Config scaffold written to {cfg_path}")
            print()
            print("  NEXT STEPS:")
            print(f"  1. Edit {cfg_path} — fill in TODO values")
            print(f"  2. Add credentials to ~/.Hermes/credentials/")
            print(f"     (openrouter.key, exa.json, brave.json at minimum)")
            print(f"  3. Run: spaice-agent doctor {agent_id}")

    return 0


# ---------------------------------------------------------------------------
# uninstall
# ---------------------------------------------------------------------------

def cmd_uninstall(args: argparse.Namespace) -> int:
    agent_id = args.agent_id
    hook_dir = _hook_dir(agent_id)
    config_dir = _config_dir(agent_id)

    removed = []
    kept = []

    if hook_dir.exists():
        if args.keep_backup:
            backup = hook_dir.with_name(
                hook_dir.name + f".uninstall-{int(datetime.now().timestamp())}"
            )
            shutil.move(str(hook_dir), str(backup))
            print(f"Hook moved to {backup}")
            removed.append(str(hook_dir))
        else:
            shutil.rmtree(hook_dir)
            removed.append(str(hook_dir))
    else:
        print(f"No hook at {hook_dir} — nothing to uninstall")

    if args.purge:
        if config_dir.exists():
            shutil.rmtree(config_dir)
            removed.append(str(config_dir))
            print(f"✗ Purged config + state at {config_dir}")
    else:
        if config_dir.exists():
            kept.append(str(config_dir))

    print(f"✓ Uninstalled spaice-{agent_id}")
    if kept:
        print(f"  Kept (use --purge to remove):")
        for p in kept:
            print(f"    {p}")
    return 0


# ---------------------------------------------------------------------------
# list
# ---------------------------------------------------------------------------

def _list_installed_agents() -> List[dict]:
    """Return list of installed agents with their manifest data."""
    hooks_root = Path.home() / ".Hermes" / "hooks"
    if not hooks_root.exists():
        return []
    agents = []
    for entry in sorted(hooks_root.iterdir()):
        manifest = entry / ".spaice-install.json"
        if manifest.exists():
            try:
                data = json.loads(manifest.read_text())
                data["_hook_dir"] = str(entry)
                agents.append(data)
            except Exception:
                pass
    return agents


def cmd_list(args: argparse.Namespace) -> int:
    agents = _list_installed_agents()
    if not agents:
        print("No spaice-* agents installed.")
        return 0

    current_ver = _get_version()
    print(f"Installed agents (spaice-agent {current_ver}):")
    print()
    for a in agents:
        agent_id = a["agent_id"]
        ver = a.get("package_version", "?")
        installed = a.get("installed_at", "?")
        has_config = _config_path(agent_id).exists()
        mark = "✓" if ver == current_ver else "⚠"
        cfg_mark = "config" if has_config else "NO CONFIG"
        print(f"  {mark} {agent_id:20s}  shim={ver:8s}  {cfg_mark}  installed={installed[:19]}")
    if any(a.get("package_version") != current_ver for a in agents):
        print()
        print("  ⚠ Some shims are stale. Run `spaice-agent upgrade` to refresh.")
    return 0


# ---------------------------------------------------------------------------
# upgrade
# ---------------------------------------------------------------------------

def cmd_upgrade(args: argparse.Namespace) -> int:
    if not args.skip_pip:
        print("→ pip install --upgrade --editable <current install>")
        pkg_root = Path(__file__).parent.parent
        try:
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "-e", str(pkg_root)],
                check=True,
            )
        except subprocess.CalledProcessError as exc:
            print(f"✗ pip install failed: {exc}", file=sys.stderr)
            return 1

    agents = _list_installed_agents()
    if not agents:
        print("No spaice-* agents installed; nothing to refresh.")
        return 0

    agent_ids = [a["agent_id"] for a in agents]
    print(f"→ Refreshing {len(agent_ids)} hook shim(s): {', '.join(agent_ids)}")
    for agent_id in agent_ids:
        fake_args = argparse.Namespace(
            agent_id=agent_id, force=True, with_config=False,
        )
        cmd_install(fake_args)

    # Also refresh bundled skills if already installed (stale manifest means user
    # wants them kept in sync with package version)
    bundled_manifest = _hermes_skills_dir() / ".spaice-bundled-manifest.json"
    if bundled_manifest.exists():
        print(f"→ Refreshing bundled skills (package v{_get_version()})")
        cmd_skills(argparse.Namespace(skills_action="bundled-install", force=True))

    # Also refresh vendored antigravity bundle if already installed
    ag_manifest = _antigravity_dir() / ".spaice-antigravity-manifest.json"
    if ag_manifest.exists() or _antigravity_dir().exists():
        print(f"→ Refreshing antigravity vendored bundle (package v{_get_version()})")
        cmd_skills(argparse.Namespace(skills_action="antigravity-install", force=True))

    print(f"✓ Upgrade complete. Package version: {_get_version()}")
    return 0


# ---------------------------------------------------------------------------
# version
# ---------------------------------------------------------------------------

def cmd_version(args: argparse.Namespace) -> int:
    print(_get_version())
    return 0


# ---------------------------------------------------------------------------
# doctor
# ---------------------------------------------------------------------------

def cmd_doctor(args: argparse.Namespace) -> int:
    agent_id = args.agent_id
    hook_dir = _hook_dir(agent_id)
    ok = True

    def check(label: str, passed: bool, detail: str = "") -> None:
        nonlocal ok
        mark = "✓" if passed else "✗"
        print(f"  {mark} {label}" + (f"  ({detail})" if detail else ""))
        if not passed:
            ok = False

    print(f"Doctor: spaice-{agent_id}")
    check("Hook dir exists", hook_dir.exists(), str(hook_dir))
    check("handler.py exists", (hook_dir / "handler.py").exists())
    check("HOOK.yaml exists", (hook_dir / "HOOK.yaml").exists())

    manifest_path = hook_dir / ".spaice-install.json"
    check("Install manifest exists", manifest_path.exists())

    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text())
            installed_ver = manifest.get("package_version", "?")
            current_ver = _get_version()
            check(
                "Shim version matches package",
                installed_ver == current_ver,
                f"shim={installed_ver} pkg={current_ver}",
            )
        except Exception as exc:
            check("Manifest parses", False, str(exc))

    try:
        import spaice_agent  # noqa: F401
        check("spaice_agent importable", True)
    except ImportError as exc:
        check("spaice_agent importable", False, str(exc))

    # BuildGuard v1 — governance middleware must be importable
    try:
        from spaice_agent.orchestrator import BuildGuard, BuildGuardDecision  # noqa: F401
        check("BuildGuard v1 active (pipeline enforcement)", True)
    except ImportError as exc:
        check("BuildGuard v1 active (pipeline enforcement)", False, str(exc))

    # Config file exists
    cfg_path = _config_path(agent_id)
    check("Config file exists", cfg_path.exists(), str(cfg_path))

    # Config loadable (deeper check — YAML parse + schema validate)
    if cfg_path.exists():
        try:
            from spaice_agent.config import load_agent_config
            load_agent_config(agent_id)
            check("Agent config loads + validates", True)
        except Exception as exc:
            check("Agent config loads + validates", False, str(exc))

    # Bundled skills — hard check (vetted, shipped with package)
    bundled_manifest = Path.home() / ".hermes" / "skills" / "spaice" / ".spaice-bundled-manifest.json"
    if bundled_manifest.exists():
        try:
            m = json.loads(bundled_manifest.read_text())
            skills_present = len(m.get("skills", []))
            check(
                "Bundled vetted skills installed",
                skills_present >= 3,
                f"{skills_present} skills — {', '.join(m.get('skills', []))}",
            )
        except Exception as exc:
            check("Bundled vetted skills readable", False, str(exc))
    else:
        check(
            "Bundled vetted skills installed",
            False,
            "run `spaice-agent skills bundled-install`",
        )

    # Antigravity skill library (standardised — vendored at pinned commit)
    antigravity_dir = Path.home() / ".hermes" / "skills" / "antigravity"
    if antigravity_dir.exists():
        skill_count = len(list(antigravity_dir.glob("*/SKILL.md")))
        check("Antigravity library installed", skill_count > 0,
              f"{skill_count} skills at {antigravity_dir}")
    else:
        check(
            "Antigravity library installed",
            False,
            "run `spaice-agent skills antigravity-install`",
        )

    # ------------------------------------------------------------------
    # Phase 3A — Memory vault + BuildGuard health
    # ------------------------------------------------------------------
    # Only meaningful once config is loadable (memory_root comes from there).
    if cfg_path.exists():
        try:
            from spaice_agent.config import load_agent_config
            _cfg = load_agent_config(agent_id)
        except Exception:
            _cfg = None

        if _cfg is not None:
            vault_root = Path(_cfg.memory_root).expanduser()
            check(
                "Memory vault root exists",
                vault_root.is_dir(),
                str(vault_root),
            )
            if vault_root.is_dir():
                check(
                    "Memory vault root writable",
                    os.access(vault_root, os.W_OK),
                    str(vault_root),
                )
                for sub in ("_inbox", "_continuity", "_dashboard"):
                    check(
                        f"Vault {sub}/ present",
                        (vault_root / sub).is_dir(),
                        str(vault_root / sub),
                    )

    # BuildGuard log dir (holds openrouter-*.jsonl) must be writable when present.
    # Created lazily on first pipeline call, so its absence is informational.
    build_log_dir = Path.home() / ".spaice-agents" / agent_id / "logs"
    if build_log_dir.is_dir():
        check(
            "BuildGuard log dir writable (openrouter-*.jsonl)",
            os.access(build_log_dir, os.W_OK),
            str(build_log_dir),
        )
    else:
        # Info only — no failure. BuildGuard mkdirs on first call.
        print(f"  · BuildGuard log dir not yet created  (will appear at {build_log_dir} on first pipeline call)")

    # BuildGuard exemption file MUST NOT linger (tactical escape-hatch only)
    exemption_path = Path.home() / ".spaice-agents" / agent_id / "build-exemption.yaml"
    check(
        "BuildGuard exemption absent (no lingering escape-hatch)",
        not exemption_path.exists(),
        str(exemption_path) if exemption_path.exists() else "",
    )

    return 0 if ok else 1


# ---------------------------------------------------------------------------
# skills — manage the bundled + optional skill libraries
# ---------------------------------------------------------------------------

BUNDLED_SKILLS = [
    "gsd",
    "self-improvement",
    "instinct-learner",
    "joe-guidelines",
    "spaice-build-stack",
    "pdf",
    "docx",
    "xlsx",
    "pptx",
    "gmail",
]


def _bundled_skills_src() -> Path:
    """Path to the packaged bundled skills directory."""
    return Path(__file__).parent / "bundled_skills"


def _hermes_skills_dir() -> Path:
    """Target dir for spaice-agent bundled skills.

    Uses ``~/.hermes/skills/spaice/`` — a first-party category that Hermes
    discovers automatically (any subdir under ~/.hermes/skills/ scanned).
    Separate from `openclaw-imports/` so it's clear these are packaged
    with spaice-agent and refreshed on `spaice-agent upgrade`.
    """
    return Path.home() / ".hermes" / "skills" / "spaice"


def _antigravity_dir() -> Path:
    return Path.home() / ".hermes" / "skills" / "antigravity"


def cmd_skills(args: argparse.Namespace) -> int:
    action = args.skills_action

    # ---- bundled (vetted, shipped with package) ----
    if action == "bundled-install":
        src = _bundled_skills_src()
        dest = _hermes_skills_dir()
        if not src.exists():
            print(f"✗ Bundled skills not found at {src} (package install broken?)")
            return 1
        dest.mkdir(parents=True, exist_ok=True)
        installed = 0
        for skill_name in BUNDLED_SKILLS:
            skill_src = src / skill_name
            skill_dst = dest / skill_name
            if not skill_src.exists():
                print(f"  ⚠ {skill_name} missing in package — skipped")
                continue
            if skill_dst.exists():
                shutil.rmtree(skill_dst)
            shutil.copytree(skill_src, skill_dst)
            installed += 1
        # Write a manifest
        manifest = {
            "installed_at": datetime.now(timezone.utc).isoformat(),
            "package_version": _get_version(),
            "skills": BUNDLED_SKILLS,
            "source": "spaice_agent.bundled_skills",
        }
        (dest / ".spaice-bundled-manifest.json").write_text(
            json.dumps(manifest, indent=2)
        )
        print(f"✓ Installed {installed}/{len(BUNDLED_SKILLS)} bundled skills at {dest}")
        for s in BUNDLED_SKILLS:
            print(f"    - {s}")
        return 0

    if action == "bundled-status":
        dest = _hermes_skills_dir()
        manifest_path = dest / ".spaice-bundled-manifest.json"
        if not manifest_path.exists():
            print("Bundled skills: NOT INSTALLED")
            print("  Run: spaice-agent skills bundled-install")
            return 1
        manifest = json.loads(manifest_path.read_text())
        current = _get_version()
        stale = manifest.get("package_version") != current
        print(f"Bundled skills: INSTALLED")
        print(f"  Path:    {dest}")
        print(f"  Pkg ver: {manifest.get('package_version')} {'⚠ stale' if stale else ''}")
        print(f"  Skills:  {', '.join(manifest.get('skills', []))}")
        print(f"  Installed: {manifest.get('installed_at')}")
        if stale:
            print(f"\n  Package upgraded (now v{current}).")
            print(f"  Refresh: spaice-agent skills bundled-install")
        return 0

    # ---- antigravity (vendored bundle, pinned commit, shipped with package) ----
    if action == "antigravity-install":
        src = _bundled_skills_src() / "antigravity"
        dest = _antigravity_dir()
        if not src.exists():
            print(f"✗ Antigravity bundle not found at {src} (package install broken?)")
            return 1
        if dest.exists() and not args.force:
            count = len(list(dest.glob("*/SKILL.md")))
            print(f"Already installed at {dest} ({count} skills).")
            print("Use --force to reinstall, or `spaice-agent upgrade` to pick up new bundle versions.")
            return 0
        if dest.exists() and args.force:
            shutil.rmtree(dest)
        print(f"→ Installing {sum(1 for _ in src.glob('*/SKILL.md'))} vendored skills to {dest}...")
        shutil.copytree(src, dest)
        # Write manifest
        upstream_md = src / "UPSTREAM.md"
        manifest = {
            "installed_at": datetime.now(timezone.utc).isoformat(),
            "package_version": _get_version(),
            "source": "spaice_agent.bundled_skills.antigravity",
            "upstream": "github.com/sickn33/antigravity-awesome-skills",
            "upstream_notes": upstream_md.read_text() if upstream_md.exists() else "",
        }
        (dest / ".spaice-antigravity-manifest.json").write_text(
            json.dumps(manifest, indent=2)
        )
        count = len(list(dest.glob("*/SKILL.md")))
        print(f"✓ Installed {count} skills at {dest}")
        print(f"  Upgrade via: spaice-agent upgrade")
        return 0

    if action == "antigravity-update":
        # Update = reinstall from vendored bundle (picks up new package version)
        args.force = True
        args.skills_action = "antigravity-install"
        return cmd_skills(args)

    if action == "antigravity-remove":
        dest = _antigravity_dir()
        if not dest.exists():
            print("Not installed — nothing to remove.")
            return 0
        shutil.rmtree(dest)
        print(f"✓ Removed {dest}")
        return 0

    if action == "antigravity-status":
        dest = _antigravity_dir()
        manifest_path = dest / ".spaice-antigravity-manifest.json"
        if not dest.exists():
            print("Antigravity library: NOT INSTALLED")
            print("  Install with: spaice-agent skills antigravity-install")
            return 1
        count = len(list(dest.glob("*/SKILL.md")))
        size_mb = sum(
            f.stat().st_size for f in dest.rglob("*") if f.is_file()
        ) // (1024 * 1024)
        print(f"Antigravity library: INSTALLED")
        print(f"  Path:   {dest}")
        print(f"  Skills: {count}")
        print(f"  Size:   {size_mb} MB")
        if manifest_path.exists():
            m = json.loads(manifest_path.read_text())
            current = _get_version()
            stale = m.get("package_version") != current
            print(f"  Pkg ver: {m.get('package_version')} {'⚠ stale' if stale else ''}")
            print(f"  Source:  {m.get('source')}")
            if stale:
                print(f"\n  Package upgraded (now v{current}).")
                print(f"  Refresh: spaice-agent skills antigravity-install --force")
        return 0

    # ---- status summary ----
    if action == "status":
        print("Skill library status")
        print("─" * 50)
        # Bundled
        bundled_manifest = _hermes_skills_dir() / ".spaice-bundled-manifest.json"
        if bundled_manifest.exists():
            m = json.loads(bundled_manifest.read_text())
            stale = m.get("package_version") != _get_version()
            mark = "⚠" if stale else "✓"
            print(f"  {mark} Bundled (vetted): {len(m.get('skills', []))} skills "
                  f"— pkg v{m.get('package_version')}")
        else:
            print(f"  ✗ Bundled (vetted): NOT INSTALLED")
        # Antigravity (vendored, standardised)
        ag_manifest = _antigravity_dir() / ".spaice-antigravity-manifest.json"
        ag = _antigravity_dir()
        if ag_manifest.exists():
            m = json.loads(ag_manifest.read_text())
            stale = m.get("package_version") != _get_version()
            mark = "⚠" if stale else "✓"
            count = len(list(ag.glob("*/SKILL.md")))
            print(f"  {mark} Antigravity (vendored): {count} skills "
                  f"— pkg v{m.get('package_version')}")
        elif ag.exists():
            count = len(list(ag.glob("*/SKILL.md")))
            print(f"  ⚠ Antigravity (vendored): {count} skills (no manifest — reinstall)")
        else:
            print(f"  ✗ Antigravity (vendored): NOT INSTALLED")
        return 0

    print(f"Unknown action: {action}")
    return 1


# ---------------------------------------------------------------------------
# vault — scaffold/check/status
# ---------------------------------------------------------------------------

def _resolve_vault_paths(agent_id: Optional[str]):
    """Resolve VaultPaths for agent_id, with helpful errors."""
    from spaice_agent.memory.paths import VaultNotFoundError, VaultPaths

    if not agent_id:
        print("✗ agent_id required (pass as positional argument)", file=sys.stderr)
        return None
    try:
        return VaultPaths.for_agent(agent_id, create_agent_dir=True)
    except VaultNotFoundError as exc:
        print(f"✗ {exc}", file=sys.stderr)
        print(f"  Create the vault root first: mkdir -p ~/{agent_id}", file=sys.stderr)
        return None


def cmd_vault(args: argparse.Namespace) -> int:
    from spaice_agent.memory.vault import (
        is_scaffolded,
        scaffold_vault,
    )

    vp = _resolve_vault_paths(args.agent_id)
    if vp is None:
        return 1

    action = args.vault_action

    if action == "scaffold":
        # Only mutate the filesystem when NOT in dry-run — ensure_skeleton
        # creates directories, which violates the dry-run contract otherwise.
        if not args.dry_run:
            vp.ensure_skeleton()
        elif not vp.inbox.exists():
            # Dry-run against a missing skeleton — report what ensure_skeleton
            # would do, then stop. Don't pretend the scaffold itself would run.
            print(f"[dry-run] Vault: {vp.vault_root}")
            print(f"[dry-run] would create skeleton dirs (run without --dry-run "
                  f"to scaffold)")
            return 0
        try:
            report = scaffold_vault(
                vp,
                overwrite=args.force,
                dry_run=args.dry_run,
            )
        except Exception as exc:
            print(f"✗ scaffold failed: {exc}", file=sys.stderr)
            return 1
        prefix = "[dry-run] " if report.dry_run else ""
        print(f"{prefix}Vault: {report.vault_root}")
        print(f"{prefix}{report.summary_line()}")
        return 0

    if action == "check":
        ok = is_scaffolded(vp)
        if ok:
            print(f"✓ Vault fully scaffolded: {vp.vault_root}")
            return 0
        print(f"✗ Vault not fully scaffolded: {vp.vault_root}")
        print(f"  Run: spaice-agent vault scaffold {args.agent_id}")
        return 1

    if action == "status":
        print(f"Vault: {vp.vault_root}")
        print(f"Agent config: {vp.agent_config_dir}")
        print()
        print("Shelves:")
        for shelf in vp.shelves:
            shelf_dir = vp.shelf_path(shelf)
            if shelf_dir.exists():
                count = sum(1 for _ in shelf_dir.rglob("*.md"))
                print(f"  {shelf:20s} {count:4d} .md")
            else:
                print(f"  {shelf:20s}  (missing)")
        print()
        print("Special dirs:")
        for d in ("_inbox", "_continuity", "_dashboard", "_templates", "_archive"):
            p = vp.vault_root / d
            if p.exists():
                count = sum(1 for _ in p.rglob("*.md"))
                print(f"  {d:20s} {count:4d} .md")
            else:
                print(f"  {d:20s}  (missing)")
        return 0

    print(f"✗ Unknown vault action: {action}", file=sys.stderr)
    return 1


# ---------------------------------------------------------------------------
# mine / triage / dashboards / recall / summarise / audit
# Thin CLI wrappers around spaice_agent.memory.* modules.
# ---------------------------------------------------------------------------

def cmd_mine(args: argparse.Namespace) -> int:
    from spaice_agent.memory.mine import Miner

    vp = _resolve_vault_paths(args.agent_id)
    if vp is None:
        return 1
    try:
        miner = Miner.for_agent(args.agent_id)
        # --limit maps to max_utterances — cost control per run.
        report = miner.run(max_utterances=args.limit)
    except Exception as exc:
        print(f"✗ mine failed: {exc}", file=sys.stderr)
        return 1
    drafts = getattr(report, "drafts_written", getattr(report, "drafts", []))
    count = len(drafts) if isinstance(drafts, list) else int(drafts or 0)
    print(f"✓ Mine: {count} draft(s) written → {vp.inbox}")
    return 0


def cmd_triage(args: argparse.Namespace) -> int:
    from spaice_agent.memory.triage import Triager

    vp = _resolve_vault_paths(args.agent_id)
    if vp is None:
        return 1
    try:
        triager = Triager.for_agent(args.agent_id)
        report = triager.run(dry_run=not args.auto)
    except Exception as exc:
        print(f"✗ triage failed: {exc}", file=sys.stderr)
        return 1
    routed = getattr(report, "routed", getattr(report, "routed_count", "?"))
    flagged = getattr(report, "flagged", getattr(report, "flagged_count", "?"))
    print(f"✓ Triage: routed={routed} flagged={flagged}")
    return 0


def cmd_dashboards(args: argparse.Namespace) -> int:
    from spaice_agent.memory.dashboards import regenerate_all

    vp = _resolve_vault_paths(args.agent_id)
    if vp is None:
        return 1
    try:
        results = regenerate_all(vp.vault_root)
    except Exception as exc:
        print(f"✗ dashboards failed: {exc}", file=sys.stderr)
        return 1
    print(f"✓ Regenerated {len(results)} dashboard(s) → {vp.dashboard}")
    for r in results:
        path = getattr(r, "output_path", getattr(r, "path", r))
        print(f"    {path}")
    return 0


def cmd_recall(args: argparse.Namespace) -> int:
    from spaice_agent.memory.recall import Recaller

    vp = _resolve_vault_paths(args.agent_id)
    if vp is None:
        return 1
    try:
        recaller = Recaller.for_agent(args.agent_id)
        triggers = recaller.extract_triggers(args.text)
        if not triggers:
            # Fall back to using the raw query as a single trigger
            triggers = [args.text]
        hits = recaller.scan(triggers, max_hits=args.limit)
    except Exception as exc:
        print(f"✗ recall failed: {exc}", file=sys.stderr)
        return 1
    if not hits:
        print(f"  No matches for: {args.text!r}")
        return 0
    print(f"Top {len(hits)} match(es) for {args.text!r}:")
    for h in hits:
        path = getattr(h, "path", h)
        score = getattr(h, "score", "")
        print(f"  [{score}] {path}")
    return 0


def cmd_summarise(args: argparse.Namespace) -> int:
    import asyncio

    from spaice_agent.config import load_agent_config
    from spaice_agent.memory.summarise import summarise_session

    vp = _resolve_vault_paths(args.agent_id)
    if vp is None:
        return 1
    try:
        cfg = load_agent_config(args.agent_id)
        summary = asyncio.run(summarise_session(args.session_id, cfg))
    except Exception as exc:
        print(f"✗ summarise failed: {exc}", file=sys.stderr)
        return 1
    print(f"✓ Summary: {summary.word_count} words, ${summary.cost_usd:.4f}")
    print(f"  Written under: {vp.archive / 'sessions'}")
    return 0


def cmd_audit(args: argparse.Namespace) -> int:
    from spaice_agent.memory.audit import audit_vault

    vp = _resolve_vault_paths(args.agent_id)
    if vp is None:
        return 1
    try:
        report = audit_vault(vp.vault_root)
    except Exception as exc:
        print(f"✗ audit failed: {exc}", file=sys.stderr)
        return 1

    if args.json:
        payload = {
            "vault_root": str(vp.vault_root),
            "counts": {
                "error": sum(1 for f in report.findings if f.severity == "error"),
                "warn": sum(1 for f in report.findings if f.severity == "warn"),
                "info": sum(1 for f in report.findings if f.severity == "info"),
            },
            "findings": [
                {"severity": f.severity, "path": f.path, "message": f.message}
                for f in report.findings
            ],
        }
        print(json.dumps(payload, indent=2))
    else:
        print(f"Audit: {vp.vault_root}")
        if not report.findings:
            print("  ✓ Clean — no findings")
            return 0
        for f in report.findings:
            mark = {"error": "✗", "warn": "⚠", "info": "·"}.get(f.severity, "•")
            print(f"  {mark} [{f.severity:5s}] {f.path}: {f.message}")
    # exit 1 if any errors, else 0
    return 1 if any(f.severity == "error" for f in report.findings) else 0


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="spaice-agent",
        description="SPAICE Agent Framework management CLI",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_install = sub.add_parser("install", help="Install hook shim for an agent")
    p_install.add_argument("agent_id", help="Agent ID (e.g. jarvis, scope-bot)")
    p_install.add_argument(
        "--force", action="store_true",
        help="Overwrite existing hook without backup",
    )
    p_install.add_argument(
        "--with-config", action="store_true",
        help="Also scaffold ~/.spaice-agents/<id>/config.yaml from template",
    )
    p_install.set_defaults(func=cmd_install)

    p_uninstall = sub.add_parser(
        "uninstall", help="Remove hook (optionally also config + state)",
    )
    p_uninstall.add_argument("agent_id", help="Agent ID to remove")
    p_uninstall.add_argument(
        "--purge", action="store_true",
        help="Also delete config + state (~/.spaice-agents/<id>/)",
    )
    p_uninstall.add_argument(
        "--keep-backup", action="store_true",
        help="Rename hook dir to backup instead of deleting",
    )
    p_uninstall.set_defaults(func=cmd_uninstall)

    p_list = sub.add_parser("list", help="Show all installed agents")
    p_list.set_defaults(func=cmd_list)

    p_upgrade = sub.add_parser(
        "upgrade",
        help="Upgrade package + refresh all installed hook shims",
    )
    p_upgrade.add_argument(
        "--skip-pip", action="store_true",
        help="Skip pip reinstall (just refresh shims)",
    )
    p_upgrade.set_defaults(func=cmd_upgrade)

    p_version = sub.add_parser("version", help="Print installed package version")
    p_version.set_defaults(func=cmd_version)

    p_doctor = sub.add_parser(
        "doctor", help="Check install health for an agent",
    )
    p_doctor.add_argument("agent_id", help="Agent ID to check")
    p_doctor.set_defaults(func=cmd_doctor)

    # skills — manage bundled (vetted) + opt-in community libraries
    p_skills = sub.add_parser(
        "skills",
        help="Manage skill libraries (bundled vetted + optional community)",
    )
    p_skills.add_argument(
        "skills_action",
        choices=[
            "status",
            "bundled-install",
            "bundled-status",
            "antigravity-install",
            "antigravity-update",
            "antigravity-remove",
            "antigravity-status",
        ],
        help=(
            "status: overall summary. "
            "bundled-install: install the vetted skills (gsd, self-improvement, "
            "instinct-learner, pdf, docx, xlsx, pptx, gmail) shipped with the package. "
            "antigravity-*: manage the vendored 1,443-skill community library "
            "(pinned to a specific upstream commit; upgrades ship via `spaice-agent upgrade`)."
        ),
    )
    p_skills.add_argument(
        "--force", action="store_true",
        help="For 'install' actions: overwrite existing",
    )
    p_skills.set_defaults(func=cmd_skills)

    # vault — scaffold/check/inspect the memory vault
    p_vault = sub.add_parser(
        "vault",
        help="Manage the memory vault (scaffold, check, inspect)",
    )
    p_vault.add_argument(
        "vault_action",
        choices=["scaffold", "check", "status"],
        help=(
            "scaffold: populate empty vault skeleton with conventions, "
            "READMEs, and templates (20 files). "
            "check: report whether vault is fully scaffolded. "
            "status: show vault root path + file counts by shelf."
        ),
    )
    p_vault.add_argument("agent_id", help="Agent ID (e.g. jarvis)")
    p_vault.add_argument(
        "--force", action="store_true",
        help="For 'scaffold': overwrite existing files",
    )
    p_vault.add_argument(
        "--dry-run", action="store_true",
        help="For 'scaffold': compute actions without writing",
    )
    p_vault.set_defaults(func=cmd_vault)

    # memory pipeline commands — thin CLI wrappers around memory/ modules
    p_mine = sub.add_parser(
        "mine", help="Mine recent sessions for new facts → _inbox/ drafts",
    )
    p_mine.add_argument("agent_id", help="Agent ID")
    p_mine.add_argument("--limit", type=int, default=20,
                        help="Max user utterances to process per run (cost control)")
    p_mine.set_defaults(func=cmd_mine)

    p_triage = sub.add_parser(
        "triage", help="Triage _inbox/ drafts into canonical shelves",
    )
    p_triage.add_argument("agent_id", help="Agent ID")
    p_triage.add_argument("--auto", action="store_true",
                          help="Auto-route high-confidence drafts; flag the rest")
    p_triage.set_defaults(func=cmd_triage)

    p_dashboards = sub.add_parser(
        "dashboards", help="Regenerate auto-dashboards under _dashboard/",
    )
    p_dashboards.add_argument("agent_id", help="Agent ID")
    p_dashboards.set_defaults(func=cmd_dashboards)

    p_recall = sub.add_parser(
        "recall", help="Query the vault for files matching text",
    )
    p_recall.add_argument("agent_id", help="Agent ID")
    p_recall.add_argument("text", help="Text to match (proper nouns, keywords)")
    p_recall.add_argument("--limit", type=int, default=5, help="Max results")
    p_recall.set_defaults(func=cmd_recall)

    p_summarise = sub.add_parser(
        "summarise", help="Summarise a session transcript → _archive/sessions/",
    )
    p_summarise.add_argument("agent_id", help="Agent ID")
    p_summarise.add_argument("session_id", help="Hermes session ID to summarise")
    p_summarise.set_defaults(func=cmd_summarise)

    p_audit = sub.add_parser(
        "audit", help="Run vault health checks (orphans, broken links, stale dashboards)",
    )
    p_audit.add_argument("agent_id", help="Agent ID")
    p_audit.add_argument("--json", action="store_true", help="Emit findings as JSON")
    p_audit.set_defaults(func=cmd_audit)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
