"""Install CLI — ``spaice-agent install <agent_id>`` writes the hook shim.

Entry point registered in pyproject.toml as ``spaice-agent``. Commands:

    spaice-agent install <agent_id>    # write hook shim to ~/.Hermes/hooks/
    spaice-agent upgrade               # reinstall package + refresh shims
    spaice-agent version               # print installed version
    spaice-agent doctor <agent_id>     # check install health

The hook shim is a 30-line file that just imports from spaice_agent.
All business logic stays in the package, so bugs fix once and ship
via ``spaice-agent upgrade``.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from importlib import metadata
from pathlib import Path
from typing import List, Optional

HOOK_SHIM_TEMPLATE = '''"""SPAICE pre-turn middleware shim — autogenerated by spaice-agent install.

Do NOT edit this file by hand. All logic lives in the spaice_agent
package; to upgrade, run ``spaice-agent upgrade``.

Generated: {generated_at}
Package version at install: {version}
Agent ID: {agent_id}
"""
from spaice_agent.hook import make_hook

AGENT_ID = "{agent_id}"
handle, register_tools = make_hook(AGENT_ID)
'''

HOOK_YAML_TEMPLATE = """name: spaice-{agent_id}
description: |
  SPAICE Agent Framework pre-turn middleware. Memory recall, search,
  and FW-1 consensus advisory. Managed by spaice-agent install.
events:
  - agent:start
"""


def _hook_dir(agent_id: str) -> Path:
    return Path.home() / ".Hermes" / "hooks" / f"spaice-{agent_id}"


def _get_version() -> str:
    try:
        return metadata.version("spaice-agent")
    except metadata.PackageNotFoundError:
        return "unknown"


def cmd_install(args: argparse.Namespace) -> int:
    agent_id = args.agent_id
    hook_dir = _hook_dir(agent_id)

    if hook_dir.exists() and not args.force:
        # Back up existing hook before overwriting
        backup = hook_dir.with_name(
            hook_dir.name + f".backup-{int(datetime.now().timestamp())}"
        )
        print(f"Backing up existing hook → {backup}")
        shutil.move(str(hook_dir), str(backup))

    hook_dir.mkdir(parents=True, exist_ok=True)

    # Write handler.py shim
    shim = HOOK_SHIM_TEMPLATE.format(
        generated_at=datetime.now(timezone.utc).isoformat(),
        version=_get_version(),
        agent_id=agent_id,
    )
    (hook_dir / "handler.py").write_text(shim)

    # Write HOOK.yaml
    (hook_dir / "HOOK.yaml").write_text(
        HOOK_YAML_TEMPLATE.format(agent_id=agent_id)
    )

    # Write install manifest for upgrade to know what's installed
    manifest = {
        "agent_id": agent_id,
        "package_version": _get_version(),
        "installed_at": datetime.now(timezone.utc).isoformat(),
        "shim_template_version": "1.0",
    }
    (hook_dir / ".spaice-install.json").write_text(
        json.dumps(manifest, indent=2)
    )

    print(f"✓ Installed spaice-{agent_id} hook at {hook_dir}")
    print(f"  Package version: {_get_version()}")
    print(f"  Shim: {hook_dir / 'handler.py'}")
    print(f"  Manifest: {hook_dir / '.spaice-install.json'}")
    return 0


def _list_installed_agents() -> List[str]:
    hooks_root = Path.home() / ".Hermes" / "hooks"
    if not hooks_root.exists():
        return []
    agents = []
    for entry in hooks_root.iterdir():
        manifest = entry / ".spaice-install.json"
        if manifest.exists():
            try:
                data = json.loads(manifest.read_text())
                agents.append(data["agent_id"])
            except Exception:
                pass
    return agents


def cmd_upgrade(args: argparse.Namespace) -> int:
    # Step 1: pip upgrade the package itself (editable install stays editable)
    if not args.skip_pip:
        print("→ pip install --upgrade --editable <current install>")
        pkg_root = Path(__file__).parent.parent  # spaice_agent/cli.py → pkg root
        try:
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "-e", str(pkg_root)],
                check=True,
            )
        except subprocess.CalledProcessError as exc:
            print(f"✗ pip install failed: {exc}", file=sys.stderr)
            return 1

    # Step 2: rewrite every installed hook's shim with the new version
    agents = _list_installed_agents()
    if not agents:
        print("No spaice-* agents installed; nothing to refresh.")
        return 0

    print(f"→ Refreshing {len(agents)} hook shim(s): {', '.join(agents)}")
    for agent_id in agents:
        fake_args = argparse.Namespace(agent_id=agent_id, force=True)
        cmd_install(fake_args)
    print(f"✓ Upgrade complete. Package version: {_get_version()}")
    return 0


def cmd_version(args: argparse.Namespace) -> int:
    print(_get_version())
    return 0


def cmd_doctor(args: argparse.Namespace) -> int:
    agent_id = args.agent_id
    hook_dir = _hook_dir(agent_id)
    ok = True

    def check(label: str, passed: bool, detail: str = "") -> None:
        nonlocal ok
        mark = "✓" if passed else "✗"
        print(f"  {mark} {label}" + (f"  ({detail})" if detail else ""))
        if not passed:
            ok = False

    print(f"Doctor: spaice-{agent_id}")
    check("Hook dir exists", hook_dir.exists(), str(hook_dir))
    check(
        "handler.py exists", (hook_dir / "handler.py").exists(),
    )
    check(
        "HOOK.yaml exists", (hook_dir / "HOOK.yaml").exists(),
    )
    manifest_path = hook_dir / ".spaice-install.json"
    check("Install manifest exists", manifest_path.exists())

    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text())
            installed_ver = manifest.get("package_version", "?")
            current_ver = _get_version()
            check(
                "Shim version matches package",
                installed_ver == current_ver,
                f"shim={installed_ver} pkg={current_ver}",
            )
        except Exception as exc:
            check("Manifest parses", False, str(exc))

    # Package importable?
    try:
        import spaice_agent  # noqa: F401
        check("spaice_agent importable", True)
    except ImportError as exc:
        check("spaice_agent importable", False, str(exc))

    # Config loadable?
    try:
        from spaice_agent.config import load_agent_config
        load_agent_config(agent_id)
        check("Agent config loads", True)
    except Exception as exc:
        check("Agent config loads", False, str(exc))

    return 0 if ok else 1


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="spaice-agent",
        description="SPAICE Agent Framework management CLI",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_install = sub.add_parser("install", help="Install hook shim for an agent")
    p_install.add_argument("agent_id", help="Agent ID (e.g. jarvis)")
    p_install.add_argument(
        "--force", action="store_true",
        help="Overwrite existing hook without backup",
    )
    p_install.set_defaults(func=cmd_install)

    p_upgrade = sub.add_parser(
        "upgrade",
        help="Upgrade package + refresh all installed hook shims",
    )
    p_upgrade.add_argument(
        "--skip-pip", action="store_true",
        help="Skip pip reinstall (just refresh shims)",
    )
    p_upgrade.set_defaults(func=cmd_upgrade)

    p_version = sub.add_parser("version", help="Print installed package version")
    p_version.set_defaults(func=cmd_version)

    p_doctor = sub.add_parser(
        "doctor", help="Check install health for an agent",
    )
    p_doctor.add_argument("agent_id", help="Agent ID to check")
    p_doctor.set_defaults(func=cmd_doctor)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
