"""Install CLI — ``spaice-agent <command>`` manages agent installs.

Entry point registered in pyproject.toml as ``spaice-agent``.

Commands:
    install <agent_id>              Write hook shim to ~/.Hermes/hooks/
        --with-config               Also scaffold ~/.spaice-agents/<id>/config.yaml
        --force                     Overwrite existing hook without backup
    uninstall <agent_id>            Remove hook; keep config (with --purge: remove both)
    upgrade                         Reinstall package + refresh all shims
    list                            Show all installed agents
    doctor <agent_id>               Check install health (9 checks)
    version                         Print installed package version

The hook shim is a 13-line autogenerated file that imports from
spaice_agent.hook. All business logic stays in the package, so bugs
fix once and ship via ``spaice-agent upgrade``.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from importlib import metadata, resources
from pathlib import Path
from typing import List, Optional

HOOK_SHIM_TEMPLATE = '''"""SPAICE pre-turn middleware shim — autogenerated by spaice-agent install.

Do NOT edit this file by hand. All logic lives in the spaice_agent
package; to upgrade, run ``spaice-agent upgrade``.

Generated: {generated_at}
Package version at install: {version}
Agent ID: {agent_id}
"""
from spaice_agent.hook import make_hook

AGENT_ID = "{agent_id}"
handle, register_tools = make_hook(AGENT_ID)
'''

HOOK_YAML_TEMPLATE = """name: spaice-{agent_id}
description: |
  SPAICE Agent Framework pre-turn middleware. Memory recall, search,
  and FW-1 consensus advisory. Managed by spaice-agent install.
events:
  - agent:start
"""


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def _hook_dir(agent_id: str) -> Path:
    return Path.home() / ".Hermes" / "hooks" / f"spaice-{agent_id}"


def _config_dir(agent_id: str) -> Path:
    return Path.home() / ".spaice-agents" / agent_id


def _config_path(agent_id: str) -> Path:
    return _config_dir(agent_id) / "config.yaml"


def _get_version() -> str:
    try:
        return metadata.version("spaice-agent")
    except metadata.PackageNotFoundError:
        return "unknown"


def _load_config_template() -> str:
    """Load the packaged config.yaml.template.

    Uses importlib.resources so it works from wheel installs, editable
    installs, and source checkouts.
    """
    try:
        return (
            resources.files("spaice_agent.templates")
            .joinpath("config.yaml.template")
            .read_text()
        )
    except (AttributeError, FileNotFoundError):
        # Fallback for older Python or non-standard installs
        pkg_root = Path(__file__).parent
        return (pkg_root / "templates" / "config.yaml.template").read_text()


# ---------------------------------------------------------------------------
# install
# ---------------------------------------------------------------------------

def cmd_install(args: argparse.Namespace) -> int:
    agent_id = args.agent_id
    hook_dir = _hook_dir(agent_id)

    if hook_dir.exists() and not args.force:
        backup = hook_dir.with_name(
            hook_dir.name + f".backup-{int(datetime.now().timestamp())}"
        )
        print(f"Backing up existing hook → {backup}")
        shutil.move(str(hook_dir), str(backup))

    hook_dir.mkdir(parents=True, exist_ok=True)

    # handler.py shim
    shim = HOOK_SHIM_TEMPLATE.format(
        generated_at=datetime.now(timezone.utc).isoformat(),
        version=_get_version(),
        agent_id=agent_id,
    )
    (hook_dir / "handler.py").write_text(shim)

    # HOOK.yaml
    (hook_dir / "HOOK.yaml").write_text(
        HOOK_YAML_TEMPLATE.format(agent_id=agent_id)
    )

    # Install manifest
    manifest = {
        "agent_id": agent_id,
        "package_version": _get_version(),
        "installed_at": datetime.now(timezone.utc).isoformat(),
        "shim_template_version": "1.0",
    }
    (hook_dir / ".spaice-install.json").write_text(
        json.dumps(manifest, indent=2)
    )

    print(f"✓ Installed spaice-{agent_id} hook at {hook_dir}")
    print(f"  Package version: {_get_version()}")

    # Optional: scaffold config.yaml
    if getattr(args, "with_config", False):
        cfg_path = _config_path(agent_id)
        if cfg_path.exists() and not args.force:
            print(f"  Config already exists at {cfg_path} — skipped (use --force to overwrite)")
        else:
            cfg_path.parent.mkdir(parents=True, exist_ok=True)
            template = _load_config_template()
            rendered = template.format(
                agent_id=agent_id,
                generated_at=datetime.now(timezone.utc).isoformat(),
                version=_get_version(),
            )
            cfg_path.write_text(rendered)
            print(f"✓ Config scaffold written to {cfg_path}")
            print()
            print("  NEXT STEPS:")
            print(f"  1. Edit {cfg_path} — fill in TODO values")
            print(f"  2. Add credentials to ~/.Hermes/credentials/")
            print(f"     (openrouter.key, exa.json, brave.json at minimum)")
            print(f"  3. Run: spaice-agent doctor {agent_id}")

    return 0


# ---------------------------------------------------------------------------
# uninstall
# ---------------------------------------------------------------------------

def cmd_uninstall(args: argparse.Namespace) -> int:
    agent_id = args.agent_id
    hook_dir = _hook_dir(agent_id)
    config_dir = _config_dir(agent_id)

    removed = []
    kept = []

    if hook_dir.exists():
        if args.keep_backup:
            backup = hook_dir.with_name(
                hook_dir.name + f".uninstall-{int(datetime.now().timestamp())}"
            )
            shutil.move(str(hook_dir), str(backup))
            print(f"Hook moved to {backup}")
            removed.append(str(hook_dir))
        else:
            shutil.rmtree(hook_dir)
            removed.append(str(hook_dir))
    else:
        print(f"No hook at {hook_dir} — nothing to uninstall")

    if args.purge:
        if config_dir.exists():
            shutil.rmtree(config_dir)
            removed.append(str(config_dir))
            print(f"✗ Purged config + state at {config_dir}")
    else:
        if config_dir.exists():
            kept.append(str(config_dir))

    print(f"✓ Uninstalled spaice-{agent_id}")
    if kept:
        print(f"  Kept (use --purge to remove):")
        for p in kept:
            print(f"    {p}")
    return 0


# ---------------------------------------------------------------------------
# list
# ---------------------------------------------------------------------------

def _list_installed_agents() -> List[dict]:
    """Return list of installed agents with their manifest data."""
    hooks_root = Path.home() / ".Hermes" / "hooks"
    if not hooks_root.exists():
        return []
    agents = []
    for entry in sorted(hooks_root.iterdir()):
        manifest = entry / ".spaice-install.json"
        if manifest.exists():
            try:
                data = json.loads(manifest.read_text())
                data["_hook_dir"] = str(entry)
                agents.append(data)
            except Exception:
                pass
    return agents


def cmd_list(args: argparse.Namespace) -> int:
    agents = _list_installed_agents()
    if not agents:
        print("No spaice-* agents installed.")
        return 0

    current_ver = _get_version()
    print(f"Installed agents (spaice-agent {current_ver}):")
    print()
    for a in agents:
        agent_id = a["agent_id"]
        ver = a.get("package_version", "?")
        installed = a.get("installed_at", "?")
        has_config = _config_path(agent_id).exists()
        mark = "✓" if ver == current_ver else "⚠"
        cfg_mark = "config" if has_config else "NO CONFIG"
        print(f"  {mark} {agent_id:20s}  shim={ver:8s}  {cfg_mark}  installed={installed[:19]}")
    if any(a.get("package_version") != current_ver for a in agents):
        print()
        print("  ⚠ Some shims are stale. Run `spaice-agent upgrade` to refresh.")
    return 0


# ---------------------------------------------------------------------------
# upgrade
# ---------------------------------------------------------------------------

def cmd_upgrade(args: argparse.Namespace) -> int:
    if not args.skip_pip:
        print("→ pip install --upgrade --editable <current install>")
        pkg_root = Path(__file__).parent.parent
        try:
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "-e", str(pkg_root)],
                check=True,
            )
        except subprocess.CalledProcessError as exc:
            print(f"✗ pip install failed: {exc}", file=sys.stderr)
            return 1

    agents = _list_installed_agents()
    if not agents:
        print("No spaice-* agents installed; nothing to refresh.")
        return 0

    agent_ids = [a["agent_id"] for a in agents]
    print(f"→ Refreshing {len(agent_ids)} hook shim(s): {', '.join(agent_ids)}")
    for agent_id in agent_ids:
        fake_args = argparse.Namespace(
            agent_id=agent_id, force=True, with_config=False,
        )
        cmd_install(fake_args)
    print(f"✓ Upgrade complete. Package version: {_get_version()}")
    return 0


# ---------------------------------------------------------------------------
# version
# ---------------------------------------------------------------------------

def cmd_version(args: argparse.Namespace) -> int:
    print(_get_version())
    return 0


# ---------------------------------------------------------------------------
# doctor
# ---------------------------------------------------------------------------

def cmd_doctor(args: argparse.Namespace) -> int:
    agent_id = args.agent_id
    hook_dir = _hook_dir(agent_id)
    ok = True

    def check(label: str, passed: bool, detail: str = "") -> None:
        nonlocal ok
        mark = "✓" if passed else "✗"
        print(f"  {mark} {label}" + (f"  ({detail})" if detail else ""))
        if not passed:
            ok = False

    print(f"Doctor: spaice-{agent_id}")
    check("Hook dir exists", hook_dir.exists(), str(hook_dir))
    check("handler.py exists", (hook_dir / "handler.py").exists())
    check("HOOK.yaml exists", (hook_dir / "HOOK.yaml").exists())

    manifest_path = hook_dir / ".spaice-install.json"
    check("Install manifest exists", manifest_path.exists())

    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text())
            installed_ver = manifest.get("package_version", "?")
            current_ver = _get_version()
            check(
                "Shim version matches package",
                installed_ver == current_ver,
                f"shim={installed_ver} pkg={current_ver}",
            )
        except Exception as exc:
            check("Manifest parses", False, str(exc))

    try:
        import spaice_agent  # noqa: F401
        check("spaice_agent importable", True)
    except ImportError as exc:
        check("spaice_agent importable", False, str(exc))

    # Config file exists
    cfg_path = _config_path(agent_id)
    check("Config file exists", cfg_path.exists(), str(cfg_path))

    # Config loadable (deeper check — YAML parse + schema validate)
    if cfg_path.exists():
        try:
            from spaice_agent.config import load_agent_config
            load_agent_config(agent_id)
            check("Agent config loads + validates", True)
        except Exception as exc:
            check("Agent config loads + validates", False, str(exc))

    # Antigravity skill library (informational — not required for hook to work)
    antigravity_dir = Path.home() / ".hermes" / "skills" / "antigravity"
    if antigravity_dir.exists():
        skill_count = len(list(antigravity_dir.glob("*/SKILL.md")))
        check(
            "Antigravity skill library installed",
            skill_count > 0,
            f"{skill_count} skills at {antigravity_dir}",
        )
    else:
        # Not a hard failure — optional
        print(f"  ○ Antigravity skill library  (not installed — run `spaice-agent skills install`)")

    return 0 if ok else 1


# ---------------------------------------------------------------------------
# skills — manage the antigravity-awesome-skills library
# ---------------------------------------------------------------------------

def cmd_skills(args: argparse.Namespace) -> int:
    action = args.skills_action
    antigravity_dir = Path.home() / ".hermes" / "skills" / "antigravity"

    if action == "install":
        if antigravity_dir.exists() and not args.force:
            count = len(list(antigravity_dir.glob("*/SKILL.md")))
            print(f"Already installed at {antigravity_dir} ({count} skills).")
            print("Use --force to reinstall, or `spaice-agent skills update` to refresh.")
            return 0
        if antigravity_dir.exists() and args.force:
            shutil.rmtree(antigravity_dir)
        if not shutil.which("npx"):
            print("✗ npx not found. Install Node.js first:")
            print("    macOS:  brew install node")
            print("    Linux:  apt install nodejs npm  (or see nodejs.org)")
            return 1
        print(f"→ Installing antigravity-awesome-skills to {antigravity_dir}...")
        try:
            subprocess.run(
                ["npx", "--yes", "antigravity-awesome-skills", "--path", str(antigravity_dir)],
                check=True,
            )
        except subprocess.CalledProcessError as exc:
            print(f"✗ Install failed: {exc}")
            return 1
        count = len(list(antigravity_dir.glob("*/SKILL.md")))
        print(f"✓ Installed {count} skills at {antigravity_dir}")
        return 0

    elif action == "update":
        if not antigravity_dir.exists():
            print(f"Not installed. Run `spaice-agent skills install` first.")
            return 1
        print(f"→ Removing old install...")
        shutil.rmtree(antigravity_dir)
        print(f"→ Reinstalling latest from antigravity-awesome-skills...")
        try:
            subprocess.run(
                ["npx", "--yes", "antigravity-awesome-skills", "--path", str(antigravity_dir)],
                check=True,
            )
        except subprocess.CalledProcessError as exc:
            print(f"✗ Update failed: {exc}")
            return 1
        count = len(list(antigravity_dir.glob("*/SKILL.md")))
        print(f"✓ Updated to latest ({count} skills)")
        return 0

    elif action == "remove":
        if not antigravity_dir.exists():
            print("Not installed — nothing to remove.")
            return 0
        shutil.rmtree(antigravity_dir)
        print(f"✓ Removed {antigravity_dir}")
        return 0

    elif action == "status":
        if not antigravity_dir.exists():
            print("Antigravity skill library: NOT INSTALLED")
            print("  Install with: spaice-agent skills install")
            return 1
        count = len(list(antigravity_dir.glob("*/SKILL.md")))
        size_mb = sum(f.stat().st_size for f in antigravity_dir.rglob("*") if f.is_file()) // (1024 * 1024)
        print(f"Antigravity skill library: INSTALLED")
        print(f"  Path:   {antigravity_dir}")
        print(f"  Skills: {count}")
        print(f"  Size:   {size_mb} MB")
        return 0

    return 1


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="spaice-agent",
        description="SPAICE Agent Framework management CLI",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_install = sub.add_parser("install", help="Install hook shim for an agent")
    p_install.add_argument("agent_id", help="Agent ID (e.g. jarvis, scope-bot)")
    p_install.add_argument(
        "--force", action="store_true",
        help="Overwrite existing hook without backup",
    )
    p_install.add_argument(
        "--with-config", action="store_true",
        help="Also scaffold ~/.spaice-agents/<id>/config.yaml from template",
    )
    p_install.set_defaults(func=cmd_install)

    p_uninstall = sub.add_parser(
        "uninstall", help="Remove hook (optionally also config + state)",
    )
    p_uninstall.add_argument("agent_id", help="Agent ID to remove")
    p_uninstall.add_argument(
        "--purge", action="store_true",
        help="Also delete config + state (~/.spaice-agents/<id>/)",
    )
    p_uninstall.add_argument(
        "--keep-backup", action="store_true",
        help="Rename hook dir to backup instead of deleting",
    )
    p_uninstall.set_defaults(func=cmd_uninstall)

    p_list = sub.add_parser("list", help="Show all installed agents")
    p_list.set_defaults(func=cmd_list)

    p_upgrade = sub.add_parser(
        "upgrade",
        help="Upgrade package + refresh all installed hook shims",
    )
    p_upgrade.add_argument(
        "--skip-pip", action="store_true",
        help="Skip pip reinstall (just refresh shims)",
    )
    p_upgrade.set_defaults(func=cmd_upgrade)

    p_version = sub.add_parser("version", help="Print installed package version")
    p_version.set_defaults(func=cmd_version)

    p_doctor = sub.add_parser(
        "doctor", help="Check install health for an agent",
    )
    p_doctor.add_argument("agent_id", help="Agent ID to check")
    p_doctor.set_defaults(func=cmd_doctor)

    # skills — manage the antigravity-awesome-skills library
    p_skills = sub.add_parser(
        "skills",
        help="Manage the antigravity-awesome-skills library (1,443+ skills)",
    )
    p_skills.add_argument(
        "skills_action",
        choices=["install", "update", "remove", "status"],
        help="Action: install (first time), update (refresh to latest), remove, or status",
    )
    p_skills.add_argument(
        "--force", action="store_true",
        help="For 'install': overwrite existing library",
    )
    p_skills.set_defaults(func=cmd_skills)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
